ignore = [
    "turbo_docs.toml",
    "node_modules",
    "repodata",
    ".git",
    ".env",
    "venv",
    "public",
    ".next",
    "package-lock.json",
    "tsconfig.json",
    "tailwind.config.js",
    "package.json",
    "next.config.js",
    "requirements.txt",
    "pnpm-lock.yaml",
    "__pycache__",
    "images",
    "next-env.d.ts",
    "README.md",
    ".gitignore",
    # "index.py",
    # "Navbar.tsx",
    # "Skills.tsx",
    "assets",
    # "ChatInterface.tsx",
    # "ProjectPage.tsx",
]