ignore = [
    "turbo_docs.toml",
    "node_modules",
    ".git",
    ".env",
    "venv",
    "public",
    ".next",
    "package-lock.json",
    "tsconfig.json",
    "requirements.txt",
    "pnpm-lock.yaml",
    "app/favicon.ico",
    "__pycache__",
    "images",
    "next-env.d.ts",
    "README.md",
    ".gitignore",
    # "index.py",
    "Navbar.tsx",
    "Skills.tsx",
    "assets",
]