ignore = [
    "turbo_docs.toml",
    "node_modules",
    ".git",
    "venv",
    "public",
    ".next",
    "package-lock.json",
    "pnpm-lock.yaml",
    "app/favicon.ico",
    "__pycache__",
    "images",
    "next-env.d.ts",
    "README.md",
    ".gitignore",
    # "index.py",
    # "services.py",
    "config.py",
]